seed_everything: true
trainer:
  devices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  accumulate_grad_batches: 1
  accelerator: gpu
  precision: 32
  gradient_clip_val: 1.0
  strategy: ddp_sharded
model:
  input_shape:
    - 64
    - 88
    - 3
  embedding_dim: 256
  num_embeddings: 256
  hidden_dims:
    - 128
    - 256
    - 512
  classifier_units:
    - 128
    - 64
    - 32
    - 16
    - 8
    - 4
data:
  batch_size: 256
  num_workers: 64
  prefetch_factor: 6