seed_everything: true
trainer:
  # devices:
  # - 0
  # - 1
  # - 2
  # - 3
  accumulate_grad_batches: 1
  # accelerator: gpu
  precision: 32
  gradient_clip_val: 1.0
  # strategy: ddp
  max_epochs: 50
model:
  input_shape: 306
  max_sequence_length: 48
data:
  max_sequence_length: 48
  normalize: False
  substract: True
  batch_size: 256
  num_workers: 4
  prefetch_factor: 2