seed_everything: true
trainer:
  devices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  accumulate_grad_batches: 1
  accelerator: gpu
  precision: 32
  gradient_clip_val: 1.0
  strategy: ddp_sharded
model:
  input_dim: 43824
  hidden_dims:
    - 1024
    - 512
    - 256
data:
  batch_size: 8
  num_workers: 64
  prefetch_factor: 2