seed_everything: true
trainer:
  devices:
  - 4
  - 5
  - 6
  - 7
  accumulate_grad_batches: 1
  accelerator: gpu
  precision: 32
  gradient_clip_val: 1.0
  strategy: ddp
  max_epochs: -1
model:
  input_shape: 264
  max_sequence_length: 48
  num_dim: 3
  # hidden_dims: 
  # - 512
  # - 256
  # - 128
  classifier_units:
  - 1024
  - 512
  - 256
  latent_dim: 1024
  before_classifier_dim: 1024
data:
  max_sequence_length: 48
  normalize: False
  substract: True
  batch_size: 256
  num_workers: 8
  prefetch_factor: 32